### ISSUE TITLE
Bundling confusion in build mode

### ISSUE THREAD

**Issue by aseem2625** [lukeed/inferno-starter#7]
Hi @lukeed 
**Goal:**
I'm currently building on top of your inferno-starter which is currently PWA-SPA starter project. I'm thinking to extend your repository to other features like lazy loading, SSR, redux, some server related advance things in separate branches, so that inferno-starter kit has more to provide to the community since we've currently much lesser projects in inferno-js available on github to learn.

**Referring branch:**
https://github.com/aseem2625/inferno-starter/tree/lazyload

**Routes file:**
https://github.com/aseem2625/inferno-starter/blob/lazyload/src/views/index.js

**Issue:**
Check routes file, Lazy loading(code splitting) is working just in run time mode using ```npm run watch``` and respective chunks are being created. However, I'm facing an issue in ```npm run build``` where webpack is failing to consider modules written with ```getComponent``` - so no chunks in build mode and neither they're included in app.hash.js.

**Resources:**
1) [Code Splitting with Webpack](https://infernojs.org/docs/guides/routing)
2) [Webpack - require.ensure](https://webpack.js.org/guides/code-splitting-async/#require-ensure-)

Spent a lot of time, can you please help?

**Comment by aseem2625** [comment]
@lukeed 
Spent some more time. Found that ```babili``` plugin is the culprit.
On removing,   ``` isProd && babel.presets.push('babili');```, code splitting works fine in build mode as well. (Check below post for using babili)

**However, one more issue** still exist. It's not letting the chunks have custom name. May be some other plugin messing up.

**Comment by aseem2625** [comment]
To use babili, below seems better for now.

Adding it just before ```UglifyJsPlugin```
```
const BabiliPlugin = require("babili-webpack-plugin");
new BabiliPlugin({
	babili: {
		presets: [
			[
				require('babel-preset-babili'),
				{
					mangle: { topLevel: true },
					deadcode: true,
					removeConsole: true
				},
			],
		],
	},
}),

```

**1. No ```babili```, my chunks sizes**
```
894B 0.dbc4ef107f0c5e7eb180.js
321B 1.dbc4ef107f0c5e7eb180.js
1.6K 2.dbc4ef107f0c5e7eb180.js
2.0K 3.dbc4ef107f0c5e7eb180.js
4.2K  app.dbc4ef107f0c5e7eb180.js
68K vendor.dbc4ef107f0c5e7eb180.js

```

**2. Using ```babili``` as told above in this comment. Note the slight trim in ```0.js```and** ```2.js```.
```
893B 0.dbc4ef107f0c5e7eb180.js
321B 1.dbc4ef107f0c5e7eb180.js
1.5K 2.dbc4ef107f0c5e7eb180.js
2.0K 3.dbc4ef107f0c5e7eb180.js
4.2K app.dbc4ef107f0c5e7eb180.js
68K vendor.dbc4ef107f0c5e7eb180.js
```

3. **Adding ```babili``` plugin below uglify**
```

893B 0.dbc4ef107f0c5e7eb180.js
321B 1.dbc4ef107f0c5e7eb180.js
1.5K 2.dbc4ef107f0c5e7eb180.js
2.0K 3.dbc4ef107f0c5e7eb180.js
4.2K app.dbc4ef107f0c5e7eb180.js
74K vendor.dbc4ef107f0c5e7eb180.js
```
Note the increase in size of ```vendor.js``` and note the issue at https://github.com/webpack-contrib/babili-webpack-plugin/issues/8

**Comment by lukeed** [comment]
Hey there!

For proper chunk-support, you have to actually configure your `config/webpack.js` to use/expect chunk files.

Here's a [webpack example](https://github.com/webpack/webpack/tree/master/examples/chunkhash#webpackconfigjs). 

For our setup, that also means editing `config/setup.js` to include the additional `common.js` chunk, which extracts the webpack runtime.

**Comment by aseem2625** [comment]
@lukeed You're right.
Just added it as below and works fine.

```
output: {
	path: dist,
	chunkFilename : '[name].[hash].js', // added for chunk created via code splitting
	filename: '[name].[hash].js',
	publicPath: '/'
},

```

@lukeed 
Also, did you get a chance to think about ```babili``` while code splitting otherwise the approach in your original repo, makes it treat lazy loading modules as unused modules and it removes them before code splitting could happen?

**Comment by lukeed** [comment]
You should be using `[chunkhash]` for both `filename` and `chunkFilename` keys. You also don't need to include `[name]` as part of your `chunkFilename` if you don't want.

You don't really have to worry about `babili` 😄 

I should probably remove it since Babili only minifies ES2015+ code... The current setup compiles to ES5, so Babili isn't even useful there.
