### ISSUE TITLE
Tree shaking: Issue for history

### ISSUE THREAD

**Issue by aseem2625** [lukeed/inferno-starter#8]
Hey @lukeed 

With the following [code](https://github.com/lukeed/inferno-starter/blob/master/config/babel.js#L3)
it should be doing tree shaking successfully.

But I'm using just `import { createBrowserHistory } from 'history';`
However, my build is having `createHashHistory` and `createMemoryHistory` in the final build

![image](https://user-images.githubusercontent.com/6055628/27081336-88394120-505d-11e7-9481-c751956035f2.png)

This is happening because of 
```
		entry: {
			app: './src/client.js',
			vendor: ['inferno', 'inferno-router', 'history']
		},
```

However, I had to write this `import createBrowserHistory from 'history/createBrowserHistory';`
AND removing `'history'` from vendor's array OR making it like this below works fine
```
vendor: ['inferno', 'inferno-router', 'history/createBrowserHistory']
```

But as the project scales and more dependencies come in, it's difficult to do `'history/createBrowserHistory'` kind of thing manually.

Any idea what's the best way to add history in vendor.js ?

**Comment by aseem2625** [comment]
Or using following is better than writing vendor: ['inferno', 'inferno-router', 'history']
```
		new webpack.optimize.CommonsChunkPlugin({
			name:'vendor',
			// minChunks: module => /node_modules/.test(module.resource)
			minChunks: function (module) {
				// this assumes your vendor imports exist in the node_modules directory
				return module.context && module.context.indexOf('node_modules') !== -1;
			}
		}),
		new webpack.optimize.CommonsChunkPlugin({
			name: 'manifest' //But since there are no more common modules between them we end up with just the runtime code included in the manifest file
		}),
```

But still I would have to do `import createBrowserHistory from 'history/createBrowserHistory';` TO avoid unused history modules to get inside build

**Comment by aseem2625** [comment]
I think `babili` should be able to help. I'll check it with that and close this issue if it worked.
In issue  https://github.com/lukeed/inferno-starter/issues/7,  you suggested me to remove babili

**Comment by lukeed** [comment]
Hey, sorry about the delay!

I'll have time to play with this tomorrow. But initial thoughts:

`babili` won't make a difference here -- at least not in treeshaking.

You _can_ import all `node_modules` into `vendor`, but this isn't something I want to ship by default.

It should be `import browser from 'history/createBrowserHistory'`. (I need to update the code.) This is because the `history` module itself [will load all three modules](https://github.com/ReactTraining/history/blob/master/modules/index.js) -- each one has to be loaded in order to be `export`ed. This is unique to `history` package and you won't have to do this for most vendor/third-party libs.

**Comment by aseem2625** [comment]
Yeah `babili` didn't make difference for `history`. But in general, it does reduce the size.. Helpful when lot of external dependencies on libraries like react-table which provides lot of functionalities but only some is used.

**Comment by lukeed** [comment]
Yeah, `babili` can help the overall size reduction, but not always && for different reasons.

I assume my suggestion worked for you -- glad to hear!

**Comment by aseem2625** [comment]
@lukeed Yeah `history/createBrowserHistory` was the thing I was using to avoid inclusion of hash and memory history and babili didn't help here. You're right, in general, babili can help in reduction but not always.
